<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/css/adminCSS/admin.css">
    <link rel="shortcut icon" href="/images/bmw_logo.png" type="image/png">
    <title>Admin</title>
</head>

<body>

        <div class="login-page">
            <div class="form">
                <form class="login-form" action="/admin" method="post">
                    <input type="text" id="login" name="login" placeholder="Логин"/>
                    <input type="text" id="password" name="password" placeholder="Пароль"/>
                    <button type="submit" id="submitButton">Отправить</button>
                </form>
            </div>
        </div>

</body>
</html>